name: "Terraform Deploy"
on:
  workflow_dispatch:
env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
  ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}
jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: "Terraform Init"
        run: terraform init
      - name: "Terraform Format"
        run: terraform fmt -check
      - name: "Terraform Plan"
        id: tf-plan
        run: |
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          
          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi
      - name: "Terraform Apply"
        run: terraform apply -auto-approve tfplan